app/forms/student_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, HiddenField, DateField, SelectField
from wtforms.validators import DataRequired


class StudentForm(FlaskForm):
    id = HiddenField('Id')
    last_name = StringField('Last Name', validators=[DataRequired()])
    first_name = StringField('First Name', validators=[DataRequired()])
    other_names = StringField('Other Names')
    phone_number = StringField('Phone Number')
    email_address = StringField('Email Address')
    date_of_birth = DateField('Date of Birth', validators=[DataRequired()])
    address = StringField('Address')


class StudentBindingModel(object):
    id = None
    last_name = None
    first_name = None
    other_names = None
    phone_number = None
    email_address = None
    date_of_birth = None
    address = None


class StudentRankForm(FlaskForm):
    id = HiddenField('Id')
    student_id = HiddenField('Student Id')
    rank_id = SelectField('Rank', coerce=int, validators=[DataRequired()])


class StudentPaymentForm(FlaskForm):
    id = HiddenField('Id')
    student_id = HiddenField('Student Id')
    payment_item_id = SelectField('Payment', coerce=int, validators=[DataRequired()])

app/views/student.py
from flask import Blueprint, render_template, redirect, url_for, flash, jsonify
from ..forms import StudentForm, StudentBindingModel, PersonForm, StudentRankForm, StudentPaymentForm
from ..services.student_service import *
from ..services.rank_service import get_all_ranks
from ..services.finance_service import get_all_payment_items


student = Blueprint('student', __name__)


@student.route('/student')
def index():
    students = get_all_students()
    return render_template('student/index.html', title='Students', items=students)


@student.route('/student/details/<studentid>')
def details(studentid):
    student = get_student_by_id(studentid)
    return render_template('student/details.html', title='Student Details', student=student)


@student.route('/student/create', methods=['GET', 'POST'])
@student.route('/student/edit/<studentid>', methods=['GET', 'POST'])
def save(studentid=None):
    title = 'Create'
    back_url = url_for('student.index')
    student_obj = StudentBindingModel()
    form = StudentForm()
    if studentid is not None:
        title = 'Edit'
        back_url = url_for('student.details', studentid=studentid)
        student_obj = get_student_binding_model(studentid)
        form = StudentForm(obj=student_obj)
    if form.validate_on_submit():
        form.populate_obj(student_obj)
        try:
            save_student(student_obj)
            return redirect(back_url)
        except:
            flash('An Error Occurred!')
    return render_template('student/create.html', title=title, form=form, back_url=back_url)


@student.route("/student/delete/<studentid>")
def delete(studentid):
    try:
        delete_student(studentid)
        success = True
    except:
        success = False

    data = {
        'success': success
    }
    resp = jsonify(data)
    return resp


@student.route("/student/<studentid>/addparent", methods=['GET', 'POST'])
@student.route("/student/<studentid>/editparent/<parentid>", methods=['GET', 'POST'])
def add_parent(studentid, parentid=None):
    title = 'Create'
    person = Person()
    form = PersonForm()
    if form.validate_on_submit():
        form.populate_obj(person)
        try:
            save_parent(person, studentid)
            return redirect(url_for('student.details', studentid=studentid))
        except:
            flash('An Error Occurred!')
    if parentid is not None:
        title = 'Edit'
        person = get_parent_by_id(parentid)
        form = PersonForm(obj=person)
    return render_template('student/parent.html', title=title, form=form, studentId=studentid)


@student.route("/student/<studentid>/deleteparent/<parentid>")
def remove_parent(studentid, parentid):
    try:
        remove_parent(parentid, studentid)
        success = True
    except:
        success = False

    data = {
        'success': success
    }
    resp = jsonify(data)
    return resp


@student.route('/student/updaterank/<studentid>', methods=['GET', 'POST'])
def update_rank(studentid):
    title = 'Update Rank'
    student_rank = StudentRank()
    d_student = get_student_by_id(studentid)
    form = StudentRankForm()
    form.rank_id.choices = [(rank.id, rank.belt_colour) for rank in get_all_ranks()
                            if rank.id not in [r.rank_id for r in d_student.ranks]]
    if form.validate_on_submit():
        form.populate_obj(student_rank)
        try:
            add_student_rank(student_rank)
            return redirect(url_for('student.update_rank', studentid=studentid))
        except:
            flash('An Error Occurred!')
    form.student_id.data = studentid
    return render_template('student/updaterank.html', title=title, form=form, student=d_student)


@student.route('/student/removerank/<id>')
def remove_student_rank(id):
    try:
        remove_rank(id)
        success = True
    except:
        success = False

    return jsonify({'success': success})


@student.route('/student/payment/<studentid>', methods=['GET', 'POST'])
def make_payment(studentid):
    title = 'Payments';
    student_payment = StudentPayment()
    d_student = get_student_by_id(studentid)
    form = StudentPaymentForm()
    form.payment_item_id.choices = [(item.id, item.full_description()) for item in get_all_payment_items()]
    if form.validate_on_submit():
        form.populate_obj(student_payment)
        try:
            add_student_payment(student_payment)
            return redirect(url_for('student.make_payment', studentid=studentid))
        except:
            flash('An Error Occured!')
    form.student_id.data = studentid
    return render_template('student/payments.html', title=title, form=form, student=d_student)


@student.route('/student/removepayment/<id>')
def remove_student_payment(id):
    try:
        remove_payment(id)
        success = True
    except:
        success = False

    return jsonify({'success': success})

app/templates/student/create.html
{% extends "./_layout.html" %}

{% block links %}
    <script src="https://cdn.jsdelivr.net/npm/gijgo@1.9.6/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://cdn.jsdelivr.net/npm/gijgo@1.9.6/css/gijgo.min.css" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}

<div class="row">
    <div class="col-8">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">{{ title }} Student</h3>
            </div>
            <div class="card-body">
                <form class="form" method="post">
                    {{ form.hidden_tag() }}
                    {{ form.id }}
                    <div class="form-group">
                        <label class="form-label">Last Name</label>
                        {{ form.last_name(class_='form-control', placeholder='Enter Last Name') }}
                        {% if form.last_name.errors %}
                          <br>
                          {% for error in form.last_name.errors %}
                            <span style="color:red">[{{error}}]</span>
                          {% endfor %}
                      {% endif %}
                    </div>
                    <div class="form-group">
                        <label class="form-label">First Name</label>
                        {{ form.first_name(class_='form-control', placeholder='Enter First Name') }}
                        {% if form.first_name.errors %}
                          <br>
                          {% for error in form.first_name.errors %}
                            <span style="color:red">[{{error}}]</span>
                          {% endfor %}
                      {% endif %}
                    </div>
                    <div class="form-group">
                        <label class="form-label">Other Names</label>
                        {{ form.other_names(class_='form-control', placeholder='Enter Other Names') }}
                        {% if form.other_names.errors %}
                          <br>
                          {% for error in form.other_names.errors %}
                            <span style="color:red">[{{error}}]</span>
                          {% endfor %}
                      {% endif %}
                    </div>
                    <div class="form-group">
                        <label class="form-label">Date of Birth</label>
                        {{ form.date_of_birth(class_='form-control birth-date', placeholder='Enter Date of Birth') }}
                        {% if form.date_of_birth.errors %}
                          <br>
                          {% for error in form.date_of_birth.errors %}
                            <span style="color:red">[{{error}}]</span>
                          {% endfor %}
                      {% endif %}
                    </div>
                    <div class="form-group">
                        <label class="form-label">Phone Number</label>
                        {{ form.phone_number(class_='form-control', placeholder='Enter Phone Number') }}
                        {% if form.phone_number.errors %}
                          <br>
                          {% for error in form.phone_number.errors %}
                            <span style="color:red">[{{error}}]</span>
                          {% endfor %}
                      {% endif %}
                    </div>
                    <div class="form-group">
                        <label class="form-label">Email Address</label>
                        {{ form.email_address(class_='form-control', placeholder='Enter Email Address') }}
                        {% if form.email_address.errors %}
                          <br>
                          {% for error in form.email_address.errors %}
                            <span style="color:red">[{{error}}]</span>
                          {% endfor %}
                      {% endif %}
                    </div>
                    <div class="form-group">
                        <label class="form-label">Home Address</label>
                        {{ form.address(class_='form-control', placeholder='Enter Home Address') }}
                        {% if form.address.errors %}
                          <br>
                          {% for error in form.address.errors %}
                            <span style="color:red">[{{error}}]</span>
                          {% endfor %}
                      {% endif %}
                    </div>
                    <div class="form-footer">
                        <a href="{{ back_url }}" class="btn btn-secondary">Cancel</a>
                        <button type="submit" class="btn btn-success">Save</button>

                  </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block scripts %}

<script type="text/javascript">

    $(document).ready(function(){
        $('#date_of_birth').datepicker({
            uiLibrary: 'bootstrap4',
            format: 'yyyy-mm-dd'
        });
    });

</script>

{% endblock %}

app/templates/student/details.html
{% extends "./_layout.html" %}

{% block content %}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">
                    <a class="btn btn-outline-secondary" href="{{ url_for('student.index') }}"><i class="fa fa-chevron-left"></i> Back To List</a>
                    <a href="{{ url_for('student.save', studentid=student.id) }}" class="btn btn-outline-warning"><i class="fa fa-edit"></i> Edit</a>
                    <a href="{{ url_for('student.update_rank', studentid=student.id) }}" class="btn btn-outline-primary"><i class="fe fe-award"></i> Update Rank</a>
                    <a href="{{ url_for('student.make_payment', studentid=student.id) }}" class="btn btn-outline-success"><i class="fe fe-dollar-sign"></i> Payments</a>
                </h3>
            </div>
            <div class="card-body">
                <p>
                    Student Number :
                    <b>{{ student.id }}</b>
                </p>
                <p>
                    Student Name :
                    <b>{{ ("%s %s %s" % (student.person.last_name, student.person.first_name, student.person.other_names)) }}</b>
                </p>
                <p>
                    Current Rank :
                    <b>{{ student.current_rank() }}</b>
                </p>
                <p>
                    Date of Birth :
                    <b>{{ student.date_of_birth }}</b>
                </p>
                {% if student.person.phone_number %}
                <p>
                    Phone Number :
                    <b>{{ student.person.phone_number }}</b>
                </p>
                {% endif %}
                {% if student.person.email_address %}
                <p>
                    Email Address :
                    <b>{{ student.person.email_address }}</b>
                </p>
                {% endif %}
                {% if student.address %}
                <p>
                    Home Address :
                    <b>{{ student.address }}</b>
                </p>
                {% endif %}
                <p>
                    Date Joined :
                    <b>{{ student.date_joined }}</b>
                </p>
                <hr>
                {% if student.parents %}
                    <h3>Parents Information</h3>
                    {% for parent in student.parents %}
                    <p>
                        Parent Name:
                        <b>{{ ("%s %s %s" % (parent.last_name, parent.first_name, parent.other_names)) }}</b>
                    </p>
                    <p>
                        Phone Number:
                        <b>{{ parent.phone_number }}</b>
                    </p>
                    <p>
                        Email Address:
                        <b>{{ parent.email_address }}</b>
                    </p>
                    <a href="{{ url_for('student.add_parent', studentid=student.id, parentid=parent.id) }}" class="btn btn-outline-warning btn-sm">Edit Parent</a>
                    <a href="" data-parentid="{{ parent.id }}" class="btn btn-outline-danger btn-sm remove-parent">Remove Parent</a>
                    <hr>
                    {% endfor %}
                {% endif %}

                <a href="{{ url_for('student.add_parent', studentid=student.id) }}" class="btn btn-primary"> Add Parent</a>
            </div>
        </div>
    </div>
</div>


{% endblock %}

{% block scripts %}

<script type="text/javascript">

    $(document).ready(function () {
        $('.remove-parent').on('click', function () {
            var studentid = '{{ student.id }}';
            var parentid = $(this).attr('data-studentId');
            var url = '/student/' + studentid + '/deleteparent/' + parentid;
            var title = "Remove This Parent?"

            confirmDelete(url, title);
        });

    });

</script>

{% endblock %}

app/templates/student/index.html
{% extends "./_layout.html" %}

{% block content %}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">{{ title }}</h3>
                <div class="card-options">
                    <a href="{{ url_for('student.save') }}" class="btn btn-primary"><i class="fa fa-plus"></i> Add New Student</a>
                </div>
            </div>
            <div class="card-body">
            <div class="table-responsive">
                <table class="table card-table table-bordered page-table">
                    <thead>
                        <tr>
                            <th>Student Number</th>
                            <th>Student Name</th>
                            <th>Date Joined</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for item in items %}
                        <tr>
                            <td>{{ item.id }}</td>
                            <td>{{ ("%s %s" % (item.person.last_name, item.person.first_name)) }}</td>
                            <td>{{ item.date_joined }}</td>
                            <td>
                                <a href="{{ url_for('student.details', studentid=item.id) }}", class="btn btn-outline-secondary btn-sm"><i class="fa fa-eye"></i> Details</a>
                                <a data-studentId="{{item.id}}" class="btn btn-outline-danger btn-sm delete-item"><i class="fa fa-trash"></i> Delete</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

{% block scripts %}

<script type="text/javascript">

    $(document).ready(function () {

        $('.delete-item').on('click', function (){
           var id = $(this).attr('data-studentId');
           var url = '/student/delete/' + id;
           var title = "Delete This Student?"

            confirmDelete(url, title);
        });

    });

</script>

{% endblock %}

app/templates/student/parent.html
{% extends "./_layout.html" %}

{% block content %}
<div class="row">
    <div class="col-8">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">{{ title }} Parent</h3>
            </div>
            <div class="card-body">
                <form class="form" method="post">
                    {{ form.hidden_tag() }}
                    {{ form.id }}
                    <div class="form-group">
                        <label class="form-label">Last Name</label>
                        {{ form.last_name(class_='form-control', placeholder='Enter Last Name') }}
                        {% if form.last_name.errors %}
                          <br>
                          {% for error in form.last_name.errors %}
                            <span style="color:red">[{{error}}]</span>
                          {% endfor %}
                      {% endif %}
                    </div>
                    <div class="form-group">
                        <label class="form-label">First Name</label>
                        {{ form.first_name(class_='form-control', placeholder='Enter First Name') }}
                        {% if form.first_name.errors %}
                          <br>
                          {% for error in form.first_name.errors %}
                            <span style="color:red">[{{error}}]</span>
                          {% endfor %}
                      {% endif %}
                    </div>
                    <div class="form-group">
                        <label class="form-label">Other Names</label>
                        {{ form.other_names(class_='form-control', placeholder='Enter Other Names') }}
                        {% if form.other_names.errors %}
                          <br>
                          {% for error in form.other_names.errors %}
                            <span style="color:red">[{{error}}]</span>
                          {% endfor %}
                      {% endif %}
                    </div>
                    <div class="form-group">
                        <label class="form-label">Phone Number</label>
                        {{ form.phone_number(class_='form-control', placeholder='Enter Phone Number') }}
                        {% if form.phone_number.errors %}
                          <br>
                          {% for error in form.phone_number.errors %}
                            <span style="color:red">[{{error}}]</span>
                          {% endfor %}
                      {% endif %}
                    </div>
                    <div class="form-group">
                        <label class="form-label">Email Address</label>
                        {{ form.email_address(class_='form-control', placeholder='Enter Email Address') }}
                        {% if form.email_address.errors %}
                          <br>
                          {% for error in form.email_address.errors %}
                            <span style="color:red">[{{error}}]</span>
                          {% endfor %}
                      {% endif %}
                    </div>
                    <div class="form-footer">
                        <a href="{{ url_for('student.details', studentid=studentId) }}" class="btn btn-secondary">Cancel</a>
                        <button type="submit" class="btn btn-success">Save</button>

                  </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

app/templates/student/payments.html
{% extends "./_layout.html" %}

{% block content %}

<div class="row">
    <div class="col-12">

        <div class="card">
            <div class="card-header">
                <a href="{{ url_for('student.details', studentid=student.id) }}" class="btn btn-outline-secondary"><i class="fa fa-chevron-left"></i> Go Back To Student Details</a>
            </div>
            <div class="card-body">
                <form class="form-inline" method="post">
                    {{ form.hidden_tag() }}
                    <div class="form-group">
                        <label class="form-label">Select Payment Item : </label>
                        &nbsp;
                        {{ form.payment_item_id(class_='form-control', style='width:350px') }}
                        &nbsp;&nbsp;
                        <button type="submit" class="btn btn-success">Complete Payment</button>
                    </div>
                </form>
            </div>
        </div>

        <div class="card">
            <div class="card-header">
                <h3 class="card-title">{{ student.full_name() }}'s Payment History</h3>
            </div>
            <div class="card-body">
            <div class="table-responsive">
                <table class="table card-table table-bordered page-table">
                    <thead>
                        <tr>
                            <th>Description</th>
                            <th>Price</th>
                            <th>Payment Date</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for item in student.payments %}
                        <tr>
                            <td>{{ item.payment_item.description }}</td>
                            <td>{{ '${:04.2f}'.format(item.payment_item.price) }}</td>
                            <td>{{ '{:%Y-%m-%d %H:%M}'.format(item.payment_date) }}</td>
                            <td>
                                <a data-id="{{item.id}}" class="btn btn-outline-danger btn-sm delete-item"><i class="fa fa-trash"></i> Remove</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block scripts %}

<script type="text/javascript">

    $(document).ready(function () {

        $('.delete-item').on('click', function (){
           var id = $(this).attr('data-id');
           var url = '/student/removepayment/' + id;
           var title = "Remove this Payment from Student's History?"

            confirmDelete(url, title);
        });

    });

</script>

{% endblock %}

app/templates/student/updaterank.html
{% extends "./_layout.html" %}

{% block content %}

<div class="row">
    <div class="col-12">

        <div class="card">
            <div class="card-header">
                <a href="{{ url_for('student.details', studentid=student.id) }}" class="btn btn-outline-secondary"><i class="fa fa-chevron-left"></i> Go Back To Student Details</a>
            </div>
            <div class="card-body">
                <form class="form-inline" method="post">
                    {{ form.hidden_tag() }}
                    <div class="form-group">
                        <label class="form-label">Update Student Rank : </label>
                        &nbsp;
                        {{ form.rank_id(class_='form-control', style='width:120px') }}
                        &nbsp;
                        <button type="submit" class="btn btn-success">Update</button>
                    </div>
                </form>
            </div>
        </div>

        <div class="card">
            <div class="card-header">
                <h3 class="card-title">{{ student.full_name() }}'s Ranks</h3>
            </div>
            <div class="card-body">
            <div class="table-responsive">
                <table class="table card-table table-bordered page-table">
                    <thead>
                        <tr>
                            <th>Belt Colour</th>
                            <th>Date Attained</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for item in student.ranks %}
                        <tr>
                            <td>{{ item.rank.belt_colour }}</td>
                            <td>{{ '{:%Y-%m-%d %H:%M}'.format(item.date_attained) }}</td>
                            <td>
                                <a data-id="{{item.id}}" class="btn btn-outline-danger btn-sm delete-item"><i class="fa fa-trash"></i> Remove</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block scripts %}

<script type="text/javascript">

    $(document).ready(function () {

        $('.delete-item').on('click', function (){
           var id = $(this).attr('data-id');
           var url = '/student/removerank/' + id;
           var title = "Remove this Rank from Student?"

            confirmDelete(url, title);
        });

    });

</script>

{% endblock %}