app/forms/paymentitem.py
from flask_wtf import FlaskForm
from wtforms import StringField, HiddenField, FloatField
from wtforms.validators import DataRequired


class PaymentItemForm(FlaskForm):
    id = HiddenField('Id')
    description = StringField('Description', validators=[DataRequired()])
    price = FloatField('Price', validators=[DataRequired()])

app/views/finance.py
from flask import Blueprint, render_template, redirect, url_for, flash, jsonify, request
# from app.models import PaymentItem
from app.forms import PaymentItemForm
from ..services.finance_service import *

finance = Blueprint('finance', __name__)


@finance.route('/finance')
def index():
    # begin = request.args.get('begin', )
    begin = request.args.get('begin', None)
    end = request.args.get('end', None)
    if begin is not None and end is not None:
        payments = get_all_payments_in_range(begin, end)
    else:
        payments = get_all_payments()
    range = {'Begin': begin or '', 'End': end or ''}
    return render_template('finance/index.html', title='Finance', items=payments, range=range)


@finance.route('/finance/items')
def paymentitems():
    payment_items = get_all_payment_items()
    return render_template('finance/paymentitem.html', title='Payment Item', items=payment_items)


@finance.route('/finance/create', methods=['GET', 'POST'])
@finance.route('/finance/edit/<itemid>', methods=['GET', 'POST'])
def save(itemid=None):
    title = 'Create'
    item = PaymentItem()
    form = PaymentItemForm()
    if itemid is not None:
        title = 'Edit'
        # fetch payment item
        item = get_payment_item_by_id(itemid)
        form = PaymentItemForm(obj=item)
    if form.validate_on_submit():
        form.populate_obj(item)
        try:
            save_payment_item(item)
            return redirect(url_for('finance.paymentitems'))
        except:
            flash('An Error Occurred!')
    return render_template('finance/create.html', title=title, form=form)


@finance.route("/finance/delete/<itemid>")
def delete(itemid):
    # message = None
    success = False;
    try:
        delete_payment_item(itemid)
        message = "Item " + itemid + " deleted"
        success = True
    except:
        message = "Error"

    data = {
        'message': message,
        'success': success
    }
    resp = jsonify(data)
    return resp

app/templates/finance/create.html
{% extends "./_layout.html" %}

{% block content %}

<div class="row">
    <div class="col-8">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">{{ title }} Payment Item</h3>
            </div>
            <div class="card-body">
                <form class="form" method="post">
                    {{ form.hidden_tag() }}
                    {{ form.id }}
                    <div class="form-group">
                        <label class="form-label">Description</label>
                        {{ form.description(class_='form-control', placeholder='Enter Description') }}
                        {% if form.description.errors %}
                          <br>
                          {% for error in form.description.errors %}
                            <span style="color:red">[{{error}}]</span>
                          {% endfor %}
                      {% endif %}
                    </div>
                    <div class="form-group">
                        <label class="form-label">Price</label>
                        {{ form.price(class_='form-control', placeholder='Enter Price (ex. 20, 30.25)') }}
                        {% if form.price.errors %}
                          <br>
                          {% for error in form.price.errors %}
                            <span style="color:red">[{{error}}]</span>
                          {% endfor %}
                      {% endif %}
                    </div>
                    <div class="form-footer">
                        <a href="{{ url_for('finance.paymentitems') }}" class="btn btn-secondary">Cancel</a>
                        <button type="submit" class="btn btn-success">Save</button>

                  </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

app/templates/finance/index.html
{% extends "./_layout.html" %}

{% block links %}
    <script src="https://cdn.jsdelivr.net/npm/gijgo@1.9.6/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://cdn.jsdelivr.net/npm/gijgo@1.9.6/css/gijgo.min.css" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">All Payments</h3>
                <div class="card-options">
                    <form class="form-inline" method="get">
                        <label class="form-label">Select Date Range : </label>
                        &nbsp;
                        <input class="form-control" id="start-date" name="begin" value="{{ range['Begin'] }}">
                        -to-
                        <input class="form-control" id="end-date" name="end" value="{{ range['End'] }}">
                        &nbsp;&nbsp;
                        <button type="submit" class="btn btn-success">View</button>
                    </form>

                </div>
            </div>
            <div class="card-body">
            <div class="table-responsive">
                <table class="table card-table table-bordered page-table">
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>Payment Description</th>
                            <th>Price</th>
                            <th>Student</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for item in items %}
                        <tr>
                            <td>{{ '{:%Y-%m-%d %H:%M}'.format(item.payment_date) }}</td>
                            <td>{{ item.payment_item.description }}</td>
                            <td>{{ '${:04.2f}'.format(item.payment_item.price) }}</td>
                            <td>{{ item.student.full_name() }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            </div>

        </div>
    </div>
</div>


{% endblock %}

{% block scripts %}

<script type="text/javascript">

   $(document).ready(function(){
       var today = new Date(new Date().getFullYear(), new Date().getMonth(), new Date().getDate());

        $('#start-date').datepicker({
            uiLibrary: 'bootstrap4',
            format: 'yyyy-mm-dd',
            maxDate: today
        });

        $('#end-date').datepicker({
            uiLibrary: 'bootstrap4',
            format: 'yyyy-mm-dd',
            minDate: function () {
                return $('#start-date').val();
            },
            maxDate: today
        });
    });
</script>

{% endblock %}

app/templates/finance/paymentitem.html
{% extends "./_layout.html" %}

{% block content %}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Payment Items</h3>
                <div class="card-options">
                    <a href="{{ url_for('finance.save') }}" class="btn btn-primary"><i class="fa fa-plus"></i> Add New Payment Item</a>
                </div>
            </div>
            <div class="card-body">
            <div class="table-responsive">
                <table class="table card-table table-bordered page-table">
                    <thead>
                        <tr>
                            <th>Item Description</th>
                            <th>Price</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for item in items %}
                        <tr>
                            <td>{{ item.description }}</td>
                            <td>{{ '{:04.2f}'.format(item.price) }}</td>
                            <td>
                                <a href="{{ url_for('finance.save', itemid=item.id) }}" class="btn btn-outline-warning btn-sm">Edit</a>
                                <a href="#" data-itemId="{{item.id}}" class="btn btn-outline-danger btn-sm delete-item">Delete</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            </div>

        </div>
    </div>
</div>


{% endblock %}

{% block scripts %}

<script type="text/javascript">

    $(document).ready(function () {

        $('.delete-item').on('click', function (){
           var id = $(this).attr('data-itemId');
           var url = '/finance/delete/' + id;
           var title = "Delete This Payment Item?"

            confirmDelete(url, title);
        });

    });

</script>

{% endblock %}