app/forms/class_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, HiddenField, SelectMultipleField
from wtforms.validators import DataRequired


class ClassForm(FlaskForm):
    id = HiddenField('Id')
    level_id = SelectField('Level', coerce=int, validators=[DataRequired()])
    class_day = SelectField('Class Day', validators=[DataRequired()])
    class_time = SelectField('Class Time', validators=[DataRequired()])


class ClassAttendanceForm(FlaskForm):
    id = HiddenField('Id')
    class_id = HiddenField('Class Id')
    student_id = SelectMultipleField('Student', coerce=int, validators=[DataRequired()])

app/views/classes.py
from flask import Blueprint, render_template, redirect, url_for, flash, jsonify, request
from datetime import date, datetime
from ..forms import ClassForm, ClassAttendanceForm
from ..services.class_service import *
from ..services.level_service import get_all_levels
from ..services.student_service import get_all_students


classes = Blueprint('classes', __name__)


@classes.route('/classes')
def index():
    all_classes = get_all_classes()
    return render_template('classes/index.html', title='Classes', items=all_classes)


@classes.route('/classes/create', methods=['GET', 'POST'])
@classes.route('/classes/edit/<classid>', methods=['GET', 'POST'])
def save(classid=None):
    title = 'Create'
    class_obj = Class()
    form = ClassForm()
    form.level_id.choices = [(level.id, level.description) for level in get_all_levels()]
    form.class_day.choices = [(d, d) for d in days_of_the_week()]
    form.class_time.choices = [(t, t) for t in hours_of_the_day()]
    if form.validate_on_submit():
        form.populate_obj(class_obj)
        try:
            save_class(class_obj)
            return redirect(url_for('classes.index'))
        except:
            flash('An Error Occurred!')
    if classid is not None:
        title = 'Edit'
        # fetch payment item
        class_obj = get_class_by_id(classid)
        form.id.data = class_obj.id
        form.level_id.data = class_obj.level_id
        form.class_day.data = class_obj.class_day
        form.class_time.data = class_obj.class_time
    return render_template('classes/create.html', title=title, form=form)


@classes.route("/classes/delete/<classid>")
def delete(classid):
    try:
        delete_class(classid)
        success = True
    except:
        success = False

    data = {
        'success': success
    }
    resp = jsonify(data)
    return resp


@classes.route("/classes/vacant/<day>/<time>/<id>")
def is_vacant(day, time, id):
    class_obj = get_class_by_day_time(day, time)
    vacant = True
    if class_obj is not None:
        if class_obj.id != int(id):
            vacant = False
    data = {
        'vacant': vacant
    }
    return jsonify(data)


def days_of_the_week():
    return ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']


def hours_of_the_day():
    hours = []
    start_hour = 9
    for i in range(0, 13):
        hour = start_hour + i
        if hour > 12:
            hours.append("%d pm" % (hour - 12))
        else:
            merdn = 'am'
            if hour == 12:
                merdn = 'pm'
            hours.append("%d %s" % (hour, merdn))
    return hours


@classes.route("/classes/attendance/<classid>", methods=['GET', 'POST'])
def class_attendance(classid):
    today = date.today()
    d_date = request.args.get('attend', today)
    if isinstance(d_date, str):
        d_date = datetime.strptime(d_date, '%Y-%m-%d').date()
    title = 'Attendance'
    class_obj = get_class_by_id(classid)
    today_attendance = [a for a in class_obj.attendance if today == a.date_attended]
    date_attendance = [a for a in class_obj.attendance if d_date == a.date_attended]
    form = ClassAttendanceForm()
    form.student_id.choices = [(st.id, '[{}] {}'.format(st.id, st.full_name())) for st in get_all_students()
                               if st.id not in [a.student_id for a in today_attendance]]
    if form.validate_on_submit():
        try:
            add_attendance(form)
            return redirect(url_for('classes.class_attendance', classid=classid))
        except:
            flash('An Error Occurred!')
    form.class_id.data = classid
    return render_template('classes/attendance.html', title=title, d_class=class_obj.full_description(),
                           form=form, attendance_date=d_date, items=date_attendance)


@classes.route("/classes/attendance/remove/<id>")
def delete_attendance(id):
    try:
        remove_attandance(id)
        success = True
    except:
        success = False

    data = {
        'success': success
    }
    resp = jsonify(data)
    return resp

app/templates/classes/attendance.html
{% extends "./_layout.html" %}

{% block links %}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/gijgo@1.9.6/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://cdn.jsdelivr.net/npm/gijgo@1.9.6/css/gijgo.min.css" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-status bg-purple"></div>
            <div class="card-header">
                <h3 class="card-title">Mark Today's Attendance</h3>
                <div class="card-options">
                    <a href="#" class="card-options-collapse" data-toggle="card-collapse"><i class="fe fe-chevron-up"></i></a>
                </div>
            </div>
            <div class="card-body">
                <form class="form-inline"  method="post">
                    {{ form.hidden_tag() }}
                    <label class="form-label">Select Students Present : </label>
                    &nbsp;&nbsp;
                    {{ form.student_id(class_='form-control', style='width:310px') }}
                    &nbsp;&nbsp;
                    <button type="submit" class="btn btn-success">Mark Attendance</button>
                </form>
            </div>
        </div>
    </div>

    <div class="col-12">
        <div class="card">
            <div class="card-status bg-blue"></div>
            <div class="card-header">
                <h3 class="card-title">Attendance Report for {{ '{:%B %d, %Y}'.format(attendance_date) }}</h3>
                <div class="card-options">
                    <form class="form-inline" method="get">
                        <label class="form-label">Select Date Range : </label>
                        &nbsp;
                        <input type="text" class="form-control" id="attendance-date" name="attend" value="{{ attendance_date }}">
                        &nbsp;&nbsp;
                        <button type="submit" class="btn btn-primary">
                            <span class="fe fe-eye"></span> View
                        </button>
                    </form>
                </div>
            </div>
            <div class="card-body">
            <div class="table-responsive">
                <table class="table card-table table-bordered page-table">
                    <thead>
                        <tr>
                            <th>Student Id</th>
                            <th>Student Name</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for item in items %}
                        <tr>
                            <td>{{ item.student.id }}</td>
                            <td>{{ item.student.full_name() }}</td>
                            <td>
                                <a data-attendanceId="{{item.id}}" class="btn btn-outline-danger btn-sm delete-item"><i class="fe fe-trash-2"></i></a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            </div>

        </div>
    </div>
</div>


{% endblock %}

{% block scripts %}

<script type="text/javascript">

   $(document).ready(function(){
        $('#student_id').select2({
            placeholder: 'Select Students'
        });

       var today = new Date(new Date().getFullYear(), new Date().getMonth(), new Date().getDate());

        $('#attendance-date').datepicker({
            uiLibrary: 'bootstrap4',
            format: 'yyyy-mm-dd',
            maxDate: today
        });

        $('.delete-item').on('click', function (){
           var id = $(this).attr('data-attendanceId');
           var url = '/classes/attendance/remove/' + id;
           var title = "Remove This Student From Attendance?"

            confirmDelete(url, title);
        });
    });
</script>

{% endblock %}

app/templates/classes/create.html
{% extends "./_layout.html" %}

{% block content %}

<div class="row">
    <div class="col-8">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">{{ title }} Class</h3>
            </div>
            <div class="card-body">
                <form class="form" method="post" id="target">
                    {{ form.hidden_tag() }}
                    <!--{{ form.id }}-->
                    <div class="form-group">
                        <label class="form-label">Level :</label>
                        {{ form.level_id(class_='form-control', placeholder='Select Level') }}
                        {% if form.level_id.errors %}
                          <br>
                          {% for error in form.level_id.errors %}
                            <span style="color:red">[{{error}}]</span>
                          {% endfor %}
                      {% endif %}
                    </div>
                    <div class="form-group">
                        <label class="form-label">Day :</label>
                        {{ form.class_day(class_='form-control', placeholder='Select Class Day') }}
                        {% if form.class_day.errors %}
                          <br>
                          {% for error in form.class_day.errors %}
                            <span style="color:red">[{{error}}]</span>
                          {% endfor %}
                      {% endif %}
                    </div>
                    <div class="form-group">
                        <label class="form-label">Time :</label>
                        {{ form.class_time(class_='form-control', placeholder='Select Class Time') }}
                        {% if form.class_time.errors %}
                          <br>
                          {% for error in form.class_time.errors %}
                            <span style="color:red">[{{error}}]</span>
                          {% endfor %}
                      {% endif %}
                    </div>
                    <div class="form-footer">
                        <a href="{{ url_for('classes.index') }}" class="btn btn-secondary">Cancel</a>
                        <button type="button" id="save" class="btn btn-success">Save</button>

                  </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block scripts %}

<script type="text/javascript">
    $(document).ready(function () {

        $('#save').click(function(){
            // e.preventDefault();
            var day_ = $('#class_day').val();
            var time_ = $('#class_time').val();
            var id_ = $('#id').val();
            var id_val = (id_ == '')? '0': id_;
            var url = encodeURI('/classes/vacant/' + day_ + '/' + time_ + '/' + id_val);
            $.when($.get(url))
                .then(function(data) {
                if(!data.vacant){
                   swal("Class Day and Time already Exists!", {
                        icon: "warning"
                   });
                }else{
                    $('#target').submit();
                }
            });
        });

    });
</script>

{% endblock %}

app/templates/classes/index.html
{% extends "./_layout.html" %}

{% block content %}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">{{ title }}</h3>
                <div class="card-options">
                    <a href="{{ url_for('classes.save') }}" class="btn btn-primary"><i class="fa fa-plus"></i> Add New Class</a>
                </div>
            </div>
            <div class="card-body">
            <div class="table-responsive">
                <table class="table card-table table-bordered page-table">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Description</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for item in items %}
                        <tr>
                            <td>{{ item.id }}</td>
                            <td>{{ item.full_description() }}</td>
                            <td>
                                <a href="{{ url_for('classes.class_attendance', classid=item.id) }}" class="btn btn-outline-dark btn-sm">Manage Class Attendance</a>
                                <a href="{{ url_for('classes.save', classid=item.id) }}" class="btn btn-outline-warning btn-sm">Edit</a>
                                <a data-classId="{{item.id}}" class="btn btn-outline-danger btn-sm delete-item">Delete</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

{% block scripts %}

<script type="text/javascript">

    $(document).ready(function () {

        $('.delete-item').on('click', function (){
           var id = $(this).attr('data-classId');
           var url = '/classes/delete/' + id;
           var title = "Delete This Class?"

            confirmDelete(url, title);
        });

    });

</script>

{% endblock %}