app/views/finance.py
from flask import Blueprint, render_template, redirect, url_for, flash, jsonify, request
# from app.models import PaymentItem
from app.forms import PaymentItemForm
from ..services.finance_service import *

finance = Blueprint('finance', __name__)


@finance.route('/finance')
def index():
    # begin = request.args.get('begin', )
    begin = request.args.get('begin', None)
    end = request.args.get('end', None)
    if begin is not None and end is not None:
        payments = get_all_payments_in_range(begin, end)
    else:
        payments = get_all_payments()
    range = {'Begin': begin or '', 'End': end or ''}
    return render_template('finance/index.html', title='Finance', items=payments, range=range)


@finance.route('/finance/items')
def paymentitems():
    payment_items = get_all_payment_items()
    return render_template('finance/paymentitem.html', title='Payment Item', items=payment_items)


@finance.route('/finance/create', methods=['GET', 'POST'])
@finance.route('/finance/edit/<itemid>', methods=['GET', 'POST'])
def save(itemid=None):
    title = 'Create'
    item = PaymentItem()
    form = PaymentItemForm()
    if itemid is not None:
        title = 'Edit'
        # fetch payment item
        item = get_payment_item_by_id(itemid)
        form = PaymentItemForm(obj=item)
    if form.validate_on_submit():
        form.populate_obj(item)
        try:
            save_payment_item(item)
            return redirect(url_for('finance.paymentitems'))
        except:
            flash('An Error Occurred!')
    return render_template('finance/create.html', title=title, form=form)


@finance.route("/finance/delete/<itemid>")
def delete(itemid):
    # message = None
    success = False;
    try:
        delete_payment_item(itemid)
        message = "Item " + itemid + " deleted"
        success = True
    except:
        message = "Error"

    data = {
        'message': message,
        'success': success
    }
    resp = jsonify(data)
    return resp

app/views/home.py
from flask import Blueprint, render_template, redirect, url_for, flash
from app.forms import LoginForm
from flask_login import current_user, login_user, logout_user, login_required
from app.models import User

home = Blueprint('home', __name__)


@home.route('/')
@home.route('/index')
@login_required
def index():
    return render_template('home/index.html', title='Welcome to KungFu Master')


@home.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('home.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None or not user.check_password(form.password.data):
            flash('Invalid username or password')
            return redirect(url_for('home.login'))
        login_user(user, remember=form.remember_me.data)
        return redirect(url_for('home.index'))
    return render_template('home/login.html', form=form)


@home.route('/logout')
def logout():
    logout_user();
    return redirect(url_for('home.login'))

app/templates/_layout.html
<!doctype html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta http-equiv="Content-Language" content="en" />
    <meta name="msapplication-TileColor" content="#2d89ef">
    <meta name="theme-color" content="#4188c9">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"/>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">
    <!--<link rel="icon" href="./favicon.ico" type="image/x-icon"/>
    <link rel="shortcut icon" type="image/x-icon" href="./favicon.ico" />-->

      {% if title %}
      <title>{{ title }} - KungFu-Master</title>
      {% else %}
      <title>Welcome to KungFu-Master</title>
      {% endif %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,300i,400,400i,500,500i,600,600i,700,700i&amp;subset=latin-ext">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.min.css">
    <!--<link rel="stylesheet" href="{{ url_for('static', filename='assets/css/jquery.dataTables.min.css') }}">-->
    <!--<script src="{{ url_for('static', filename='assets/js/require.min.js') }}"></script>-->
    <script>
      // requirejs.config({
      //     baseUrl: './static'
      // });
    </script>
    <!-- Dashboard Core -->
    <link href="{{ url_for('static', filename='assets/css/dashboard.css') }}" rel="stylesheet" />
      <script src="{{ url_for('static', filename='assets/js/vendors/jquery-3.2.1.min.js') }}"></script>
      <script src="{{ url_for('static', filename='assets/js/vendors/bootstrap.bundle.min.js') }}"></script>
      <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
      <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
    <!--<script src="{{ url_for('static', filename='assets/js/jquery.dataTables.min.js') }}"></script>-->
    {% block links %}
    {% endblock %}
  </head>

  <body class="">
    <div class="page">
      <div class="page-main">
        <div class="header py-4" style="padding-bottom: 0px !important;">
          <div class="container">
            <div class="d-flex">
              <a class="header-brand" href="#" >
                <!--<img src="./demo/brand/tabler.svg" class="header-brand-img" alt="tabler logo">-->
                  <h1>KungFu Master</h1>
              </a>
              <div class="d-flex order-lg-2 ml-auto">
                <div class="dropdown">
                  <a href="#" class="nav-link pr-0 leading-none" data-toggle="dropdown">

                    <span class="avatar" style="background-image: url(../static/assets/images/avatar-default.png)"></span>
                    <span class="ml-2 d-none d-lg-block">
                      <span class="text-default">Jet Lee</span>
                      <small class="text-muted d-block mt-1">Administrator</small>
                    </span>
                  </a>
                  <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                    <a class="dropdown-item" href="#">
                      <i class="dropdown-icon fe fe-settings"></i> Settings
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{{url_for('home.logout')}}">
                      <i class="dropdown-icon fe fe-log-out"></i> Sign out
                    </a>
                  </div>
                </div>
              </div>
              <a href="#" class="header-toggler d-lg-none ml-3 ml-lg-0" data-toggle="collapse" data-target="#headerMenuCollapse">
                <span class="header-toggler-icon"></span>
              </a>
            </div>
          </div>
        </div>

        <div class="header collapse d-lg-flex p-0" id="headerMenuCollapse">
          <div class="container">
            <div class="row align-items-center">

              <div class="col-lg order-lg-first">
                <ul class="nav nav-tabs border-0 flex-column flex-lg-row">
                  <li class="nav-item">
                    <a href="{{ url_for('home.index') }}" class="nav-link"><i class="fe fe-home"></i> Dashboard</a>
                  </li>
                  <li class="nav-item">
                    <a href="javascript:void(0)" class="nav-link" data-toggle="dropdown"><i class="fe fe-box"></i> Administration</a>
                    <div class="dropdown-menu dropdown-menu-arrow">
                      <a href="{{ url_for('finance.index') }}" class="dropdown-item ">Finances</a>
                      <a href="{{ url_for('finance.paymentitems') }}" class="dropdown-item ">Payment Items</a>
                      <a href="{{ url_for('rank.index') }}" class="dropdown-item ">Ranks</a>
                      <a href="{{ url_for('level.index') }}" class="dropdown-item ">Levels</a>
                    </div>
                  </li>
                  <li class="nav-item">
                    <a href="javascript:void(0)" class="nav-link" data-toggle="dropdown"><i class="fe fe-activity"></i> Classes</a>
                    <div class="dropdown-menu dropdown-menu-arrow">
                      <a href="{{ url_for('classes.index') }}" class="dropdown-item ">Manage Classes</a>
                    </div>
                  </li>
                  <li class="nav-item">
                    <a href="javascript:void(0)" class="nav-link" data-toggle="dropdown"><i class="fe fe-users"></i> Students</a>
                    <div class="dropdown-menu dropdown-menu-arrow">
                      <a href="{{ url_for('student.index') }}" class="dropdown-item ">Manage Students</a>
                    </div>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>

          <!-- Page Content Begins here -->
        <div class="my-3 my-md-5">
            <div class="container">
                <div class="page-header">
                    {% if title %}
                  <h1 class="page-title">
                    {{ title }}
                  </h1>
                    {% endif %}
                </div>
                {% with messages = get_flashed_messages() %}
                {% if messages %}
                <ul>
                    {% for message in messages %}
                    <li>{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
                {% endwith %}
                {% block content %}{% endblock %}
            </div>
        </div>
      </div>


      <footer class="footer">
        <div class="container">
          <div class="row align-items-center flex-row-reverse">

            <div class="col-12 col-lg-auto mt-3 mt-lg-0 text-center">
              Copyright © 2018 <a href="#">Kung-Fu Master School</a>. Theme by <a href="https://codecalm.net" target="_blank">codecalm.net</a> All rights reserved.
            </div>
          </div>
        </div>
      </footer>
    </div>
  </body>

</html>


<script type="application/javascript">

  $(document).ready(function(){

        $('.page-table').dataTable();
  });

  function confirmDelete(url, title) {
       swal({
           title: title,
           icon: "warning",
           buttons: true,
           dangerMode: true
       }).then((deletekey) => {
           if(deletekey){
               $.get(url, function(data){
                   if(data.success){
                       swal("Successfully deleted!", {
                            icon: "success"
                       }).then(() => {
                            location.reload(true);
                       });
                   }else{
                       swal("An Error Occurred!", {
                            icon: "error" });
                   }
               });
            }
       });
  }
</script>
{% block scripts %}
{% endblock %}